### ISSUE TITLE
Click on `C` button enters C on screen

### ISSUE THREAD

**Issue by letsintegreat** [queenCee/calC#4]
Basically, <kbd>C</kbd> button is used to Clear the current screen (not the memory), but in this case, whenever we click on <kbd>C</kbd>, a `C` char gets added on screen, which I think should not happen

**Comment by LeCeee** [comment]
Hello there! CodePatronas, long time no see I guess. 
You are right. it used to work fine earlier though. 
I'll merge your PR after reviewing.

**Comment by letsintegreat** [comment]
Ohhk cool
